### ISSUE TITLE
Can't connect after latest update

### ISSUE THREAD

**Issue by bbtufty** [Banh-Canh/docker-FMD2#4]
After the latest update I can't connect via port 6080 any more. Poking through the logs there's an importerror that websocketify doesn't exist, which might be it? It was working before the last update so I'm not sure what's changed

**Comment by Banh-Canh** [comment]
Hey, thanks for the report. The change I made was minimal so it should have impacted anything but It seems some alpine package changed versions since the last time I rebuilt the docker image and I think a newly released package broke websockify. Since I can't really pin package version with alpine package, I'm not sure I can fix it. I'll investigate some more.

For now I repushed the old image to the latest tag (like I said the change made in last commit are more about "code quality" than anything else and should have any impact at all).

I also pushed a version of my docker image with ubuntu as the base image. It works fine for me and I'll probably use it in the future just so I can pin package versions. To use this image you have to use the unstable tagged image (for now).
